/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*Para testar o script da aplicação, eu irei adicionar um ou dois filmes 
*e vereficar se está tudo ocorrendo bem.
*/
package cadastro;

import java.sql.ResultSet;
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
//Preparando para importar o banco de dados
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLSyntaxErrorException;
import java.sql.SQLNonTransientConnectionException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Guido
 */
public class cadastroFilme extends javax.swing.JFrame {
    
    private Connection conexao;
    java.sql.PreparedStatement st;
    
    /**
     * Creates new form cadastroFilme
     */
    public cadastroFilme() {
        initComponents();
        this.pack ();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //Ajustando as visibilidades dos paineis 
        telaCadastro.setVisible(false);
        jConfirmacao.setVisible(false);
        jCadastrado.setVisible(false);
        jInicio.setVisible(true);
        jBusca.setVisible(false);
        jResultado.setVisible(false);
        jEditar.setVisible(false);
        
        //Redimensionamento da tela
        this.pack();
        this.setLocationRelativeTo(null);
        
        //referenciando o banco de dados
   try{  
        Class.forName("com.mysql.cj.jdbc.Driver");
        conexao = DriverManager.getConnection("jdbc:mysql://localhost:3306/cenaflix","root","Lespaul98");
        st = conexao.prepareStatement("INSERT INTO filmes(nome,datalancamento,categoria) VALUES (?,?,?)");
  }catch (ClassNotFoundException ex){
        System.out.println("O Driver não está disponivel na biblioteca");
  }catch (SQLException ex){
        System.out.println("Sintaxe de comando errada");
  }
    }
    private void ocultarColunaID() {
        jTabelaResult.getColumnModel().getColumn(0).setMinWidth(0);
        jTabelaResult.getColumnModel().getColumn(0).setMaxWidth(0);
        jTabelaResult.getColumnModel().getColumn(0).setWidth(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInicio = new javax.swing.JPanel();
        jTituloConfirmacao2 = new javax.swing.JLabel();
        jOpcao = new javax.swing.JLabel();
        JBemVindo1 = new javax.swing.JLabel();
        btnCad = new javax.swing.JButton();
        btnBusc = new javax.swing.JButton();
        telaCadastro = new javax.swing.JPanel();
        jTituloCadastro = new javax.swing.JLabel();
        subtituloCadastro = new javax.swing.JLabel();
        nomeFilme = new javax.swing.JLabel();
        jNome = new javax.swing.JTextField();
        dataLancamento = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        jCategoria = new javax.swing.JTextField();
        btnCadastro = new javax.swing.JButton();
        jData = new javax.swing.JFormattedTextField();
        jConfirmacao = new javax.swing.JPanel();
        jTituloConfirmacao = new javax.swing.JLabel();
        confirNome = new javax.swing.JLabel();
        confirData = new javax.swing.JLabel();
        confirCategoria = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnCont = new javax.swing.JButton();
        jCadastrado = new javax.swing.JPanel();
        jTituloConfirmacao1 = new javax.swing.JLabel();
        cadastrado = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        jBusca = new javax.swing.JPanel();
        jTituloConfirmacao3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCampoBusca = new javax.swing.JTextField();
        btnBusca = new javax.swing.JButton();
        jEscolha = new javax.swing.JComboBox<>();
        jResultado = new javax.swing.JPanel();
        jTituloConfirmacao4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabelaResult = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jEditar = new javax.swing.JPanel();
        jTituloConfirmacao5 = new javax.swing.JLabel();
        jEditNome = new javax.swing.JLabel();
        jEditCat = new javax.swing.JLabel();
        jEditData = new javax.swing.JLabel();
        jCatAt = new javax.swing.JTextField();
        jNomeAt = new javax.swing.JTextField();
        btnDelet = new javax.swing.JButton();
        btnAt = new javax.swing.JButton();
        jDataAt = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jInicio.setPreferredSize(new java.awt.Dimension(418, 296));

        jTituloConfirmacao2.setBackground(new java.awt.Color(204, 204, 204));
        jTituloConfirmacao2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTituloConfirmacao2.setText("Cenaflix");
        jTituloConfirmacao2.setOpaque(true);

        jOpcao.setBackground(new java.awt.Color(255, 255, 255));
        jOpcao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jOpcao.setText("Escolha uma das opções abaixo.");
        jOpcao.setMaximumSize(new java.awt.Dimension(129, 25));
        jOpcao.setMinimumSize(new java.awt.Dimension(129, 25));
        jOpcao.setPreferredSize(new java.awt.Dimension(129, 25));

        JBemVindo1.setBackground(new java.awt.Color(255, 255, 255));
        JBemVindo1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        JBemVindo1.setText("Seja bem vindo!");
        JBemVindo1.setMaximumSize(new java.awt.Dimension(129, 25));
        JBemVindo1.setMinimumSize(new java.awt.Dimension(129, 25));
        JBemVindo1.setPreferredSize(new java.awt.Dimension(129, 25));

        btnCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCad.setText("Cadastro");
        btnCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadActionPerformed(evt);
            }
        });

        btnBusc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBusc.setText("Busca");
        btnBusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInicioLayout = new javax.swing.GroupLayout(jInicio);
        jInicio.setLayout(jInicioLayout);
        jInicioLayout.setHorizontalGroup(
            jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInicioLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioLayout.createSequentialGroup()
                        .addComponent(jTituloConfirmacao2)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioLayout.createSequentialGroup()
                        .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBusc)
                            .addComponent(jOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
            .addGroup(jInicioLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnCad)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInicioLayout.createSequentialGroup()
                    .addContainerGap(92, Short.MAX_VALUE)
                    .addComponent(JBemVindo1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(64, 64, 64)))
        );
        jInicioLayout.setVerticalGroup(
            jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloConfirmacao2)
                .addGap(93, 93, 93)
                .addComponent(jOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCad)
                    .addComponent(btnBusc))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(jInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInicioLayout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(JBemVindo1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(173, Short.MAX_VALUE)))
        );

        telaCadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTituloCadastro.setBackground(new java.awt.Color(204, 204, 204));
        jTituloCadastro.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTituloCadastro.setText("Cenaflix");
        jTituloCadastro.setOpaque(true);

        subtituloCadastro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        subtituloCadastro.setText("<html><u>CADASTRO DE FILME</u></html>");

        nomeFilme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nomeFilme.setText("Nome do Filme:");

        jNome.setBackground(new java.awt.Color(204, 204, 255));
        jNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jNome.setOpaque(true);

        dataLancamento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dataLancamento.setText("Data de Lançamento:");

        categoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        categoria.setText("Categoria:");

        jCategoria.setBackground(new java.awt.Color(204, 204, 255));
        jCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCategoria.setOpaque(true);

        btnCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastro.setText("Cadastrar");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        jData.setBackground(new java.awt.Color(204, 204, 255));
        try {
            jData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jData.setOpaque(true);

        javax.swing.GroupLayout telaCadastroLayout = new javax.swing.GroupLayout(telaCadastro);
        telaCadastro.setLayout(telaCadastroLayout);
        telaCadastroLayout.setHorizontalGroup(
            telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroLayout.createSequentialGroup()
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaCadastroLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jTituloCadastro))
                    .addGroup(telaCadastroLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(subtituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(telaCadastroLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dataLancamento)
                            .addComponent(nomeFilme)
                            .addComponent(categoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jNome)
                            .addComponent(jCategoria)
                            .addComponent(jData, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaCadastroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCadastro)
                .addGap(152, 152, 152))
        );
        telaCadastroLayout.setVerticalGroup(
            telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subtituloCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFilme)
                    .addComponent(jNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataLancamento)
                    .addComponent(jData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(telaCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoria)
                    .addComponent(jCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnCadastro)
                .addGap(23, 23, 23))
        );

        jConfirmacao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jConfirmacao.setPreferredSize(new java.awt.Dimension(418, 296));

        jTituloConfirmacao.setBackground(new java.awt.Color(204, 204, 204));
        jTituloConfirmacao.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTituloConfirmacao.setText("Cenaflix");
        jTituloConfirmacao.setOpaque(true);

        confirNome.setBackground(new java.awt.Color(204, 204, 255));
        confirNome.setMaximumSize(new java.awt.Dimension(129, 25));
        confirNome.setMinimumSize(new java.awt.Dimension(129, 25));
        confirNome.setOpaque(true);
        confirNome.setPreferredSize(new java.awt.Dimension(129, 25));

        confirData.setBackground(new java.awt.Color(204, 204, 255));
        confirData.setMaximumSize(new java.awt.Dimension(129, 25));
        confirData.setMinimumSize(new java.awt.Dimension(129, 25));
        confirData.setOpaque(true);
        confirData.setPreferredSize(new java.awt.Dimension(129, 25));

        confirCategoria.setBackground(new java.awt.Color(204, 204, 255));
        confirCategoria.setMaximumSize(new java.awt.Dimension(129, 25));
        confirCategoria.setMinimumSize(new java.awt.Dimension(129, 25));
        confirCategoria.setOpaque(true);
        confirCategoria.setPreferredSize(new java.awt.Dimension(129, 25));

        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnCont.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCont.setText("Continuar");
        btnCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jConfirmacaoLayout = new javax.swing.GroupLayout(jConfirmacao);
        jConfirmacao.setLayout(jConfirmacaoLayout);
        jConfirmacaoLayout.setHorizontalGroup(
            jConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConfirmacaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTituloConfirmacao)
                .addGap(135, 135, 135))
            .addGroup(jConfirmacaoLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jConfirmacaoLayout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCont))
                    .addComponent(confirData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jConfirmacaoLayout.setVerticalGroup(
            jConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConfirmacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloConfirmacao)
                .addGap(35, 35, 35)
                .addComponent(confirNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(confirData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(confirCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jConfirmacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar)
                    .addComponent(btnCont))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jCadastrado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCadastrado.setPreferredSize(new java.awt.Dimension(418, 296));

        jTituloConfirmacao1.setBackground(new java.awt.Color(204, 204, 204));
        jTituloConfirmacao1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTituloConfirmacao1.setText("Cenaflix");
        jTituloConfirmacao1.setOpaque(true);

        cadastrado.setBackground(new java.awt.Color(255, 255, 255));
        cadastrado.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cadastrado.setText("Filme Cadastrado!");
        cadastrado.setMaximumSize(new java.awt.Dimension(129, 25));
        cadastrado.setMinimumSize(new java.awt.Dimension(129, 25));
        cadastrado.setPreferredSize(new java.awt.Dimension(129, 25));

        btnOk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCadastradoLayout = new javax.swing.GroupLayout(jCadastrado);
        jCadastrado.setLayout(jCadastradoLayout);
        jCadastradoLayout.setHorizontalGroup(
            jCadastradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCadastradoLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(cadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCadastradoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jCadastradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCadastradoLayout.createSequentialGroup()
                        .addComponent(jTituloConfirmacao1)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCadastradoLayout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );
        jCadastradoLayout.setVerticalGroup(
            jCadastradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCadastradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloConfirmacao1)
                .addGap(56, 56, 56)
                .addComponent(cadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnOk)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jBusca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBusca.setPreferredSize(new java.awt.Dimension(418, 296));

        jTituloConfirmacao3.setBackground(new java.awt.Color(204, 204, 204));
        jTituloConfirmacao3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTituloConfirmacao3.setText("Cenaflix");
        jTituloConfirmacao3.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Digite abaixo no campo:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Escolha o formato de busca:");

        jCampoBusca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnBusca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBusca.setText("Buscar");
        btnBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaActionPerformed(evt);
            }
        });

        jEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Categoria" }));

        javax.swing.GroupLayout jBuscaLayout = new javax.swing.GroupLayout(jBusca);
        jBusca.setLayout(jBuscaLayout);
        jBuscaLayout.setHorizontalGroup(
            jBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBuscaLayout.createSequentialGroup()
                .addGroup(jBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jBuscaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jBuscaLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCampoBusca)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBuscaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBuscaLayout.createSequentialGroup()
                        .addComponent(jTituloConfirmacao3)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jBuscaLayout.createSequentialGroup()
                        .addComponent(btnBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        jBuscaLayout.setVerticalGroup(
            jBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloConfirmacao3)
                .addGap(55, 55, 55)
                .addGroup(jBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCampoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBusca)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jResultado.setPreferredSize(new java.awt.Dimension(418, 296));

        jTituloConfirmacao4.setBackground(new java.awt.Color(204, 204, 204));
        jTituloConfirmacao4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTituloConfirmacao4.setText("Cenaflix");
        jTituloConfirmacao4.setOpaque(true);

        jTabelaResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Data Lançamento", "Categoria"
            }
        ));
        jScrollPane2.setViewportView(jTabelaResult);

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jResultadoLayout = new javax.swing.GroupLayout(jResultado);
        jResultado.setLayout(jResultadoLayout);
        jResultadoLayout.setHorizontalGroup(
            jResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jResultadoLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jTituloConfirmacao4)
                .addGap(135, 135, 135))
            .addGroup(jResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jResultadoLayout.createSequentialGroup()
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jResultadoLayout.setVerticalGroup(
            jResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jResultadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloConfirmacao4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnEdit))
                .addGap(43, 43, 43))
        );

        jEditar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jEditar.setPreferredSize(new java.awt.Dimension(418, 296));

        jTituloConfirmacao5.setBackground(new java.awt.Color(204, 204, 204));
        jTituloConfirmacao5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTituloConfirmacao5.setText("Cenaflix");
        jTituloConfirmacao5.setOpaque(true);

        jEditNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEditNome.setText("Nome:");

        jEditCat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEditCat.setText("Categoria:");

        jEditData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jEditData.setText("Data Lançamento:");

        jCatAt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jNomeAt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnDelet.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDelet.setText("Deletar");
        btnDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletActionPerformed(evt);
            }
        });

        btnAt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAt.setText("Atualizar");
        btnAt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtActionPerformed(evt);
            }
        });

        try {
            jDataAt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jDataAt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jEditarLayout = new javax.swing.GroupLayout(jEditar);
        jEditar.setLayout(jEditarLayout);
        jEditarLayout.setHorizontalGroup(
            jEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditarLayout.createSequentialGroup()
                .addGroup(jEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jEditarLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEditData)
                            .addComponent(jEditNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jEditCat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelet, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCatAt)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jEditarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAt))
                            .addGroup(jEditarLayout.createSequentialGroup()
                                .addComponent(jNomeAt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jDataAt)))
                    .addGroup(jEditarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTituloConfirmacao5)
                        .addGap(68, 68, 68)))
                .addGap(67, 67, 67))
        );
        jEditarLayout.setVerticalGroup(
            jEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTituloConfirmacao5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditNome)
                    .addComponent(jNomeAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditData)
                    .addComponent(jDataAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEditCat)
                    .addComponent(jCatAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelet)
                    .addComponent(btnAt))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(telaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jConfirmacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
        //Obter os valores digitados
        //Deixei as variáveis com nome dos campos da database para não me perder
        String nome = jNome.getText();
        String datalancamento = jData.getText();
        String categoria = jCategoria.getText();
        
        //Verificar se o usuário não deixou nenhum campo vazio
        if (nome.isEmpty() || datalancamento.isEmpty() || categoria.isEmpty()){
            JOptionPane.showMessageDialog(this,"Por favor preencher todos os campos","Erro", JOptionPane.ERROR_MESSAGE);
        }else{
            //Atribuindo valores ao dados no painel de confirmação
            confirNome.setText(nome);
            confirData.setText(datalancamento);
            confirCategoria.setText(categoria);
            
            //Indo para o segundo painel
            telaCadastro.setVisible(false);
            jConfirmacao.setVisible(true);
            jCadastrado.setVisible(false);
            jInicio.setVisible(false);
            jBusca.setVisible(false);
            jResultado.setVisible(false);
            jEditar.setVisible(false);
        }  
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContActionPerformed
        // TODO add your handling code here:
        //Pegando os dados inseridos no painel anterior
        try{
            String nomeDB = confirNome.getText();
            String dataDB = confirData.getText();
            String categoriaDB = confirCategoria.getText();
            
            //Convertendo a string do campo data para DATE 
            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
            java.util.Date dataUtil = sdf.parse(dataDB);
            java.sql.Date dataSQL = new java.sql.Date(dataUtil.getTime());
            
            //Comando pata inserção de dados no MySQL
            st.setString(1,nomeDB);
            st.setDate(2,dataSQL);
            st.setString(3,categoriaDB);
            
            //Executando a inserção
            int resultado = st.executeUpdate();
            if (resultado > 0){
                //Se deu certo, esconde os paineis indesejáveis
                telaCadastro.setVisible(false);
                jConfirmacao.setVisible(false);
                jCadastrado.setVisible(true);
                jResultado.setVisible(false);
                jInicio.setVisible(false);
                jBusca.setVisible(false);
                jEditar.setVisible(false);
            }
        }catch(ParseException ex){
            JOptionPane.showMessageDialog(this,"Erro formato Data"+ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this,"Erro ao inserir o banco"+ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Algo deu errado"+ex.getMessage(),"Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnContActionPerformed
    //Criando método para limpar campos
    private void limparCampos(){
        jNome.setText("");
        jData.setText("");
        jCategoria.setText("");
    }
    
    
    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        limparCampos();
        //Configurando o botão para voltar ao primeiro painel
        jConfirmacao.setVisible(false);
        telaCadastro.setVisible(true);
        jCadastrado.setVisible(false);
        jInicio.setVisible(false);
        jBusca.setVisible(false);
        jResultado.setVisible(false);
        jEditar.setVisible(false);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        limparCampos();
        //Este botão irá fazer a mesma ação que o btnLimpar
        jConfirmacao.setVisible(false);
        telaCadastro.setVisible(false);
        jCadastrado.setVisible(false);
        jInicio.setVisible(true);
        jBusca.setVisible(false);
        jResultado.setVisible(false);
        jEditar.setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadActionPerformed
        // TODO add your handling code here:
        telaCadastro.setVisible(true);
        jConfirmacao.setVisible(false);
        jCadastrado.setVisible(false);
        jInicio.setVisible(false);
        jBusca.setVisible(false);
        jResultado.setVisible(false);
        jEditar.setVisible(false);
    }//GEN-LAST:event_btnCadActionPerformed

    private void btnBuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscActionPerformed
        // TODO add your handling code here:
        telaCadastro.setVisible(false);
        jConfirmacao.setVisible(false);
        jCadastrado.setVisible(false);
        jInicio.setVisible(false);
        jBusca.setVisible(true);
        jResultado.setVisible(false);
        jEditar.setVisible(false);
    }//GEN-LAST:event_btnBuscActionPerformed

    private void btnBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaActionPerformed
        // TODO add your handling code here:
        //Mostrando erro se caso o campo de busca estier vazio
        if (jCampoBusca.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor, preencha o campo de busca");
            return; //Estando vazio não continua a busca
        }
        //Especificando o que o combo Box irá ser atribuído
        String colunaSelecionada = jEscolha.getSelectedItem().toString();
        String colunaBanco = "";
        
        //Atribui a coluna conforme o Combo Box
        switch (colunaSelecionada) {
            case "Nome":
                colunaBanco = "nome";
                break;
            case "Categoria":
                    colunaBanco = "categoria";
                    break;
        }
        //Recupera o texto digitado no campo da busca
        String termoBusca = jCampoBusca.getText().trim();
        
        //Criando um modelo para tabela
        DefaultTableModel modelo = (DefaultTableModel) jTabelaResult.getModel();
        
        //Limpa resultados antigos
        modelo.setRowCount(0);
        
        //Definindo a consulta no SQL
        String sql = "SELECT id,nome,datalancamento, categoria FROM filmes WHERE "+colunaBanco+" LIKE ?";
    
        //Usando a conexão existente 
        try {
            st = conexao.prepareStatement(sql);
            st.setString(1,"%" + termoBusca + "%");
            
            //executa a consulta
            ResultSet rs = st.executeQuery();
            
            //Preenche e tabela com os resultados da consulta
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nome"),
                    rs.getString("datalancamento"),
                    rs.getString("categoria"),    
                });    
            }
            //Ocultando o id
            ocultarColunaID();
            
            telaCadastro.setVisible(false);
            jConfirmacao.setVisible(false);
            jCadastrado.setVisible(false);
            jInicio.setVisible(false);
            jBusca.setVisible(false);
            jResultado.setVisible(true);
            jEditar.setVisible(false);
            
        }catch (SQLSyntaxErrorException ex){
            //captura os erros de sintaze na query
            JOptionPane.showMessageDialog(null,"Erro Sintaxe SQL:\n"+ ex.getMessage());
            ex.printStackTrace();//Mostra o erro completo do console
        }catch (SQLNonTransientConnectionException ex) {
            //Capaturando erros da conexão do banco de dados
            JOptionPane.showMessageDialog(null, "Erro de conexão do banco de dados:\n"+ ex.getMessage());
            ex.printStackTrace();
        }catch(SQLException ex){
            //Captura qualquer outro erro relacionado ao banco de dados
            JOptionPane.showMessageDialog(null,
                    "Erro ao acessar o banco de dados:\n"+ ex.getMessage()+
                    "\nCódigo do erro: "+ ex.getErrorCode()+
                    "SQLState: "+ ex.getSQLState());
            ex.printStackTrace();
        }catch(Exception ex){
            //Capturando erros genéricos do que não seja do SQL
            JOptionPane.showMessageDialog(null, "Erro inesperado:\n"+ ex.getMessage());
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_btnBuscaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        telaCadastro.setVisible(false);
        jConfirmacao.setVisible(false);
        jCadastrado.setVisible(false);
        jInicio.setVisible(true);
        jBusca.setVisible(false);
        jResultado.setVisible(false);
        jEditar.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        //Obtendo os dados das linhas selecionadas
        int linha = jTabelaResult.getSelectedRow();
        
        //Verificando se alguma linha foi selecionada
        if (linha !=-1 ){
            String nome = jTabelaResult.getValueAt(linha, 1).toString();
            String data = jTabelaResult.getValueAt(linha, 2).toString();
            String cat = jTabelaResult.getValueAt(linha, 3).toString();
            
            //Preenchendo o campo Nome para edição
            jNomeAt.setText(nome);
            
            /*Convertando o campo data do SQL ####/##/## para data mask
            * que editei ##/##/####
            */
            try{
                DateTimeFormatter formatoEntrada = DateTimeFormatter.ofPattern("yyy-MM-dd");
                DateTimeFormatter formatoSaida = DateTimeFormatter.ofPattern("dd/MM/yyy");
                LocalDate dataConvertida = LocalDate.parse(data, formatoEntrada);
                jDataAt.setText(dataConvertida.format(formatoSaida));
            }catch (Exception e){
                //Caso não precise converter
                jDataAt.setText(data);
            }
            
            //Preenchendo o campo categoria
            jCatAt.setText(cat);
            
            telaCadastro.setVisible(false);
            jConfirmacao.setVisible(false);
            jCadastrado.setVisible(false);
            jInicio.setVisible(false);
            jBusca.setVisible(false);
            jResultado.setVisible(false);
            jEditar.setVisible(true);           
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um filme na tabela para editar.");
        }  
    }//GEN-LAST:event_btnEditActionPerformed

    private void atualizarTabela() throws SQLException{
        try{
            //Limpa os dados antigos
            DefaultTableModel modelo = (DefaultTableModel) jTabelaResult.getModel();
            modelo.setRowCount(0);
            
            //Consulta geral das colunas
            String sql = "SELECT * FROM filmes";
            st = conexao.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            
            //Preenchendo a tabela com dados em branco
            while (rs.next()){
                modelo.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("nome"),
                    rs.getString("datalancamento"),
                    rs.getString("categoria")
                });
            }
            
            //Ocultando o ID da tabela 
            ocultarColunaID();
            
            //Fechando as conexões
            rs.close();
            st.close();
            
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Erro ao atualizar a tabela");
        }
    }
    
    private void btnDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletActionPerformed
        // TODO add your handling code here:
        //Obtendo Ìndice da linha selecionada
        int linhaSelecionada = jTabelaResult.getSelectedRow();
        
        //Verificando se o usuário selecionou alguma linha
        if (linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Selecione um filme para deletar.");
            return;
        }
        //Pegando o ID invisível da coluna
        int id = Integer.parseInt(jTabelaResult.getValueAt(linhaSelecionada, 0).toString());
        
        //Confirmando com o usuário se deseja realmente deletar os dados
        int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja DELETAR?","Confirmação",JOptionPane.YES_NO_OPTION);
        
        //Usuário clicando em sim
        if (confirmacao == JOptionPane.YES_OPTION){
            try{
                //comando sql para deletar os dados
                String sql = "DELETE FROM filmes WHERE id = ?";
                st = conexao.prepareStatement(sql);
                st.setInt(1, id);
                
                //Executando o comando
                int linhasAfetadas = st.executeUpdate();
                
                //Verificando se deletou com sucesso
                if (linhasAfetadas > 0) {
                    JOptionPane.showMessageDialog(null, "Filme deletado com sucesso.");
                    
                    //Atualizando a tabela depois da exclusão
                    atualizarTabela();
                    telaCadastro.setVisible(false);
                    jConfirmacao.setVisible(false);
                    jCadastrado.setVisible(false);
                    jInicio.setVisible(true);
                    jBusca.setVisible(false);
                    jResultado.setVisible(false);
                    jEditar.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null,"Erro ao deletar filme.");
                }
                
                //Fechando conexão
                st.close();
                
            }catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Erro de SQL");
            } 
        }
    }//GEN-LAST:event_btnDeletActionPerformed

    private void btnAtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtActionPerformed
        // TODO add your handling code here:
       try{
            //Recuperando dados dos campos editados
            String nome = jNomeAt.getText().trim();
            String dataStr = jDataAt.getText().trim();
            String categoria = jCatAt.getText().trim();
        
        //Verificando se algum campo está em branco
            if (nome.isEmpty()|| dataStr.isEmpty()|| categoria.isEmpty()){
                JOptionPane.showMessageDialog(null,"Por favor, preencha todos os campos.");
                return;
            }
            //Convertendo a data para o formato do banco
            DateTimeFormatter formatoEntrada = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            DateTimeFormatter formatoSaida = DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDate dataConvertida = LocalDate.parse(dataStr, formatoEntrada);
            String dataSQL = dataConvertida.format(formatoSaida);
        
            //Recuperando ID da linha selecionada na tabela
            int linhaSelecionada = jTabelaResult.getSelectedRow();
            if (linhaSelecionada == -1){
                JOptionPane.showMessageDialog(null, "Selecione um filme para atualizar.");
                return;
            }
            int id = Integer.parseInt(jTabelaResult.getValueAt(linhaSelecionada, 0).toString());
        
            //Preparando o comando SQL
            String sql = "UPDATE filmes SET nome = ?, datalancamento = ?, categoria=? WHERE id = ?";
            st = conexao.prepareStatement(sql);
            st.setString(1, nome);
            st.setString(2, dataSQL);
            st.setString(3, categoria);
            st.setInt(4, id);
        
            //Executa a atualização
            int linhasAfetadas = st.executeUpdate();
            if (linhasAfetadas > 0){
                JOptionPane.showMessageDialog(null, "Filme atualizado com sucesso!");
                atualizarTabela();
                telaCadastro.setVisible(false);
                jConfirmacao.setVisible(false);
                jCadastrado.setVisible(false);
                jInicio.setVisible(true);
                jBusca.setVisible(false);
                jResultado.setVisible(false);
                jEditar.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Nenhum dado atualizado.");
                telaCadastro.setVisible(false);
                jConfirmacao.setVisible(false);
                jCadastrado.setVisible(false);
                jInicio.setVisible(true);
                jBusca.setVisible(false);
                jResultado.setVisible(false);
                jEditar.setVisible(false);
            }
            
       }catch (SQLException ex){
           JOptionPane.showMessageDialog(null, "Erro ao atualizar o Filme:\n"+ex.getMessage());
           ex.printStackTrace();
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null, "ErroInesperado"+ex.getMessage());
           ex.printStackTrace();
       }
    }//GEN-LAST:event_btnAtActionPerformed
              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JBemVindo1;
    private javax.swing.JButton btnAt;
    private javax.swing.JButton btnBusc;
    private javax.swing.JButton btnBusca;
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnCont;
    private javax.swing.JButton btnDelet;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel cadastrado;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel confirCategoria;
    private javax.swing.JLabel confirData;
    private javax.swing.JLabel confirNome;
    private javax.swing.JLabel dataLancamento;
    private javax.swing.JPanel jBusca;
    private javax.swing.JPanel jCadastrado;
    private javax.swing.JTextField jCampoBusca;
    private javax.swing.JTextField jCatAt;
    private javax.swing.JTextField jCategoria;
    private javax.swing.JPanel jConfirmacao;
    private javax.swing.JFormattedTextField jData;
    private javax.swing.JFormattedTextField jDataAt;
    private javax.swing.JLabel jEditCat;
    private javax.swing.JLabel jEditData;
    private javax.swing.JLabel jEditNome;
    private javax.swing.JPanel jEditar;
    private javax.swing.JComboBox<String> jEscolha;
    private javax.swing.JPanel jInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jNome;
    private javax.swing.JTextField jNomeAt;
    private javax.swing.JLabel jOpcao;
    private javax.swing.JPanel jResultado;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabelaResult;
    private javax.swing.JLabel jTituloCadastro;
    private javax.swing.JLabel jTituloConfirmacao;
    private javax.swing.JLabel jTituloConfirmacao1;
    private javax.swing.JLabel jTituloConfirmacao2;
    private javax.swing.JLabel jTituloConfirmacao3;
    private javax.swing.JLabel jTituloConfirmacao4;
    private javax.swing.JLabel jTituloConfirmacao5;
    private javax.swing.JLabel nomeFilme;
    private javax.swing.JLabel subtituloCadastro;
    private javax.swing.JPanel telaCadastro;
    // End of variables declaration//GEN-END:variables
}
